[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
h5py = "*"
ndindex = "*"
openssl = "*" # libcrypto, for the SHA256 hasher in versioned_hdf5/hash.pyx

[feature.build.dependencies]
# Needed for --no-build-isolation
cython = "*"
meson-python = "*"
pkg-config = "*" # Needed with meson >=1.11
setuptools-scm = "*"
pip = "*"
wheel = "*"
python-build = "*"
twine = "*"
zlib = "*"
openssl = "*" # libcrypto, for the SHA256 hasher in versioned_hdf5/hash.pyx

[feature.build.target.linux.dependencies]
gcc = "*"
patchelf = "*"

[feature.build.target.osx.dependencies]
clang = "*"
patchelf = "*"

[feature.build.target.win.dependencies]
clang = "*"
llvm-tools = "*"
pkg-config = "*" # Needed to find hdf5

[feature.build.target.win.activation.env]
CC = "clang"
LD = "llvm-ar"

[feature.build.tasks]
# Perform a regular build and install of versioned-hdf5 in the current environment
install = "python -m pip install . -v --no-build-isolation --no-dependencies"
uninstall = "python -m pip uninstall -y versioned-hdf5"
# Perform editable install, but do nothing if package was already installed by
# either 'install' or 'editable-install'. Add --force to force re-installation.
# This task is a dependency of all tasks that need versioned-hdf5 to be installed.
editable-install = "python ci/editable_install.py"
sdist = "python -m build --sdist --no-isolation"
# Build a wheel for the current platform and python only.
# For debugging only. Do not use for release; use cibuildwheel instead.
wheel = "python -m build --wheel --no-isolation"
twine-check = "twine check dist/*"
smoke = { cmd = "python ci/smoke_test.py", depends-on = ["editable-install"] }

# Absolute minimum versions of build and runtime dependencies.
# Compilation against an old stack of dependencies is very fiddly:
# - No Linux ARM nor MacOS ARM binaries available for hdf5
# - On MacOS Intel, h5py==3.8.0 fails to compile due to import issues
# - On Windows, meson fails to find libhdf5 1.10, and crashes with libhdf5 1.12.

[feature.mindeps.dependencies]
meson = "=1.2.0"
meson-python = "=0.15.0"
setuptools-scm = "=8.1"
cython = "=3.0.10"
numpy = "=1.24.4"
ndindex = "=1.5.1"
openssl = "=1.1.1s"

[feature.mindeps.target.linux-64.dependencies] # Intel
# Note: apt on Ubuntu 24.04 (ubuntu-latest github runner) installs
# hdf5=1.10.10, which however is not available on conda
hdf5 = "=1.10.6"
gcc = "=10"

# h5py=3.8.0 in conda-forge requires hdf5 >=1.12.2,<1.14.1;
# build it from sources instead.
[feature.mindeps.target.linux-64.pypi-dependencies]
h5py = "==3.8.0"

[feature.mindeps.pypi-options]
no-binary = ["h5py"]

[feature.mindeps.target.linux-aarch64.dependencies]
# No binaries available for very old versions on Linux ARM
hdf5 = "=1.12.2"
h5py = "=3.8.0"
gcc = "=10"

[feature.mindeps.target.osx.dependencies] # Both ARM and Intel
# No binaries available for very old versions on MacOS ARM
# MacOS Intel fails to compile h5py 3.8.0 from sources
hdf5 = "=1.12.2"
h5py = "=3.8.0"
clang = "=14"

[feature.mindeps.target.win-64.dependencies] # Intel
# Meson fails to detect hdf5 1.10
# hdf5 1.12 shows double-linking issues at runtime
hdf5 = "=1.14.0"
h5py = "=3.9.0"
clang = "=14"
llvm-tools = "=14"

[feature.hdf5-112]
# hdf5 1.12.2 is the minimum version supported by h5py binaries in conda-forge.
# On Windows it shows double-linking issues at runtime.
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64"]

[feature.hdf5-112.dependencies]
numpy = "=1.24.4" # Old versions of h5py trigger DeprecationWarning in newer NumPy
h5py = "=3.8.0"
hdf5 = "=1.12.2"

[feature.hdf5-114.dependencies]
hdf5 = "=1.14"

[feature.np126.dependencies]
numpy = "=1.26"
[feature.np200.dependencies]
numpy = "=2.0"

[feature.py310.dependencies]
python = "=3.10"
[feature.py311.dependencies]
python = "=3.11"
[feature.py312.dependencies]
python = "=3.12"
[feature.py313.dependencies]
python = "=3.13"
[feature.py314.dependencies]
python = "=3.14"

[feature.h5py-dev.dependencies]
numpy = "*"
hdf5 = "*"
ndindex = "*"
openssl = "*"

[feature.h5py-dev.pypi-dependencies]
h5py = { git = "https://github.com/h5py/h5py.git" }

[feature.test.dependencies]
pytest = "*"
pytest-env = "*"
hypothesis = "*"
packaging = "*"

[feature.test.tasks]
test = { cmd = "pytest", depends-on = ["editable-install"] }

[feature.filters.dependencies]
hdf5plugin = "*"

[feature.ipython.dependencies]
ipython = "*"

[feature.ipython.tasks]
ipython = { cmd = "ipython", depends-on = ["editable-install"] }

[feature.lint.dependencies]
lefthook = "*"
ruff = "*"
mypy = "*"
dprint = "*"
actionlint = "*"
shellcheck = "*" # Runs inside actionlint
pyflakes = "*" # Runs inside actionlint
codespell = "*"
blacken-docs = "*"
validate-pyproject = "*"
cython-lint = "*"
sphinx-lint = "*"
types-requests = "*"

[feature.lint.tasks]
install-git-hooks = { cmd = "lefthook install", description = "Install pre-commit hooks" }
lint = { cmd = "lefthook run pre-commit --all-files --force", description = "Run all linters" }

[feature.bench.dependencies]
asv = "*"

[feature.bench.tasks]
asv-machine = "asv machine --yes"
asv-run = { cmd = "asv run --python=same --quick --set-commit-hash $(git rev-parse HEAD)", depends-on = ["editable-install"] }

[feature.docs.dependencies]
graphviz = "*"
myst-parser = "*"
# FIXME https://github.com/sphinx-contrib/multiversion/issues/201
# sphinx-multiversion 0.2.4 is broken with Sphinx 9
sphinx = "=8"
sphinx-multiversion = "*"

[feature.docs.tasks]
docs = { cmd = "sphinx-build -M html . _build -W", cwd = "docs", depends-on = ["editable-install"] }
docs-multiversion-build = { cmd = "sphinx-multiversion . _build-multiversion/html", cwd = "docs", depends-on = ["editable-install"] }
# sphinx-multiversion only builds docs for every tag; this redirects users who visit
# ./index.html -> ./master/index.html, which is the development branch docs.
docs-multiversion-redirect = "cp docs/multiversion-index.html docs/_build-multiversion/html/index.html"
docs-multiversion = { depends-on = ["docs-multiversion-build", "docs-multiversion-redirect"] }

[environments]
default = { features = ["py314", "ipython", "build", "test", "filters", "bench"] }
bench = { features = ["py314", "build", "bench"] }
docs = { features = ["py314", "build", "docs"] }
lint = { features = ["lint"], no-default-feature = true }
mindeps = { features = ["py310", "mindeps", "build", "test", "bench"], no-default-feature = true }
hdf5-112 = { features = ["py310", "hdf5-112", "build", "test", "filters"] }
hdf5-114 = { features = ["py310", "hdf5-114", "build", "test", "filters"] }
np126 = { features = ["py310", "np126", "build", "test", "filters"] }
np200 = { features = ["py310", "np200", "build", "test", "filters"] }
py310 = { features = ["py310", "build", "test", "filters"] }
py311 = { features = ["py311", "build", "test", "filters"] }
py312 = { features = ["py312", "build", "test", "filters"] }
py313 = { features = ["py313", "build", "test", "filters"] }
py314 = { features = ["py314", "build", "test", "filters"] }
h5py-dev = { features = ["py314", "h5py-dev", "build", "test"], no-default-feature = true }
