name: Benchmarks
on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]
  workflow_dispatch: # allows you to trigger manually

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: benchmarks-${{ github.ref }}
  cancel-in-progress: true

permissions: {}
jobs:
  benchmarks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        env: ["mindeps", "bench"]
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          # get correct version from setuptools_scm
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          pixi-version: v0.72.0
          cache: true
          environments: ${{ matrix.env }}

      - name: Compile, install, and print versions
        run: pixi r -e ${{ matrix.env }} smoke

      - name: Setup asv
        run: |
          # Work around https://github.com/airspeed-velocity/asv/issues/1508
          sed -i "s/master/$(git rev-parse --abbrev-ref HEAD)/" asv.conf.json
          pixi r -e ${{ matrix.env }} asv-machine

      - name: Run Benchmarks
        run: pixi r -e ${{ matrix.env }} asv-run

      - name: Upload asv results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: asv-results-${{ matrix.env }}
          path: .asv/results
