name: Build docs
on:
  pull_request:
  workflow_dispatch:
permissions: {}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          # get correct version from setuptools_scm
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0
        with:
          pixi-version: v0.67.2
          cache: true
          environments: docs

      - name: Compile, install, and print versions
        run: pixi r -e docs smoke

      - name: Build docs
        run: pixi r -e docs docs

      - name: Build docs (multiversion)
        run: pixi r -e docs docs-multiversion
