name: Linting

on: [push, pull_request]
permissions: {}

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0
        with:
          pixi-version: v0.67.2
          cache: true
          environments: lint
      - name: Run linters
        run: pixi run lint
      - name: Check for changed files after linting
        run: git diff --exit-code
