name: Linting

on: [push, pull_request]
permissions: {}

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          pixi-version: v0.72.0
          cache: true
          environments: lint
      - name: Run linters
        run: pixi run lint
      - name: Check for changed files after linting
        run: git diff --exit-code
