name: Build and deploy docs to github pages

on:
  push:
    branches: [master]
  release:
    types: [published]
  workflow_dispatch:

permissions: {}

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# Cancel in-progress deployment jobs so only the latest one succeeds.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Always checkout master branch, even if triggered by a tag.
      # Otherwise sphinx-multiversion does not pull the master branch.
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: master
          fetch-tags: true # needed by sphinx-multiversion
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0
        with:
          pixi-version: v0.67.2
          cache: true
          environments: docs

      - name: Compile, install, and print versions
        run: pixi r -e docs smoke

      - name: Build docs
        run: pixi r -e docs docs-multiversion

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: "docs/_build-multiversion/html"

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
        id: deployment
