name: Release Python Bindings to PyPI

on:
  release:
    types: [published]
  pull_request:
  workflow_dispatch:
    inputs:
      test_pypi:
        type: boolean
        description: 'Test release: publish on test.pypi.org'
        default: false

jobs:
  build-sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - name: 💻 Checkout the repo
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: build-vhdf
          environment-file: environment.yml
          conda-remove-defaults: true

      - name: Manually sest env variables to allow conda deps to be discoverable
        shell: bash -l {0}
        run: |
          CONDA_PREFIX=$(conda info --base)/envs/build-vhdf
          echo "CONDA_PREFIX=$CONDA_PREFIX" >> $GITHUB_ENV
          echo "$CONDA_PREFIX/bin" >> $GITHUB_PATH
          echo "CPATH=$CONDA_PREFIX/include:$CPATH" >> $GITHUB_ENV
          echo "LIBRARY_PATH=$CONDA_PREFIX/lib:$LIBRARY_PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: 🚀 Install build dependencies
        run: |
          pip install build twine

      - name: 📦 Build the sdist and wheel
        run: |
          python -m build --sdist -o wheelhouse

      - name: List and check sdist
        run: |
          ls -lh wheelhouse/
          twine check wheelhouse/*

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: wheels-sdist
          path: ./wheelhouse/*.tar.gz

  build-wheels:
    name: 'Wheels: ${{ matrix.os }} ${{ matrix.arch }} ${{ matrix.python-version }}'
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.12']
        include:
          - os: ubuntu-latest
            arch: x86_64
          # - os: windows-latest
          #   arch: AMD64
          - os: macos-latest
            arch: arm64

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # get the non-merge commit for PRs

    # Install openmpi on macos
    - name: Install openmpi and hdf5 on macos
      if: matrix.os == 'macos-latest'
      run: |
        brew install open-mpi
        echo "PKG_CONFIG_PATH=$(brew --prefix)/lib/pkgconfig:$(brew --prefix)/opt/open-mpi/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "CPATH=$(brew --prefix)/include:$CPATH" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$(brew --prefix)/lib:$LIBRARY_PATH" >> $GITHUB_ENV

    # Set up python on ubuntu (build runs in containers, so can't use conda)
    # Can't use conda on macos, the binaries it installs are invalid according
    # to meson: "executables created by cpp compiler are not runnable"
    - name: 🐍 Set up Python
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      uses: actions/setup-python@v5

    - name: Set python include path on macos
      if: matrix.os == 'macos-latest'
      run: |
          echo "CPATH=$(python -c 'import sysconfig; print(sysconfig.get_path("include"))'):$CPATH" >> $GITHUB_ENV

    # Use environment-windows.yml because windows only has msmpi, not openmpi
    - name: 🐍 Set up Python
      if: matrix.os == 'windows-latest'
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        activate-environment: build-vhdf
        environment-file: environment-windows.yml
        conda-remove-defaults: true

    # Windows HDF5
    - uses: nuget/setup-nuget@v2
      if: runner.os == 'Windows'
    - uses: actions/setup-python@v5
      if: runner.os == 'Windows'
      with:
        python-version: ${{ matrix.python-version }}
    - run: bash ./ci/cibw_before_all_windows.sh "${{ github.workspace }}"
      if: runner.os == 'Windows'

    # macOS HDF5
    - run: bash ./ci/cibw_before_all_macos.sh "${{ github.workspace }}"
      if: runner.os == 'macOS'

    # Triage build
    - run: bash ./ci/triage_build.sh "${{ matrix.arch }}" "${{ github.event.pull_request.head.sha || github.sha }}" "${{ matrix.python-version }}"

    # Now actually build the wheels
    - uses: pypa/cibuildwheel@v2.22.0
      env:
        # Note that tool.cibuildwheel "skip" in pyproject.toml also limits what gets built
        CIBW_ARCHS: ${{ matrix.arch }}
        CIBW_BUILD: ${{ env.CIBW_BUILD }}
        CIBW_SKIP: ${{ env.CIBW_SKIP }}
        CIBW_BEFORE_BUILD: ${{ env.CIBW_BEFORE_BUILD }}
        CIBW_BUILD_FRONTEND: ${{ env.CIBW_BUILD_FRONTEND }}
        CIBW_PRERELEASE_PYTHONS: ${{ env.CIBW_PRERELEASE_PYTHONS }}
        CIBW_BEFORE_TEST: ${{ env.CIBW_BEFORE_TEST }}
        CIBW_BEFORE_BUILD_LINUX: yum install -y openmpi openmpi-devel zlib-devel; rpm -ql openmpi-devel
        CIBW_ENVIRONMENT_LINUX: PATH=/usr/lib64/openmpi/bin:$PATH # Make sure mpicc is on PATH
        CIBW_ENVIRONMENT_MACOS: CPATH=$HDF5_DIR/include:$CPATH

    - run: python ./ci/bundle_hdf5_whl.py wheelhouse
      if: runner.os == 'Windows'

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-${{ matrix.python-version }}
        path: ./wheelhouse/*.whl

  publish:
    name: Publish Python packages on PyPI
    if: (github.event_name == 'release' && startsWith(github.ref, 'refs/tags')) || (github.event_name == 'workflow_dispatch')
    needs: [build-sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/versioned-hdf5
    permissions:
      id-token: write
    steps:
      - name: Retrieve wheels and sdist
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: wheels/

      - name: print artifacts
        run: |
          ls -l wheels/

      - name: 🧪 Publish to PyPI Testing
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ inputs.test_pypi }}
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: wheels

      - name: 🎉 Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ !inputs.test_pypi }}
        with:
          packages-dir: wheels
