name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest  # x64
          - ubuntu-24.04-arm  # ARM
          - macos-15-intel  # x64
          - macos-latest # ARM
          - windows-latest  # x64
        env:
          - mindeps  # absolute minimum build and runtime versions;
                     # libhdf5 and h5py vary by OS and architecture
          - hdf5-112  # Python 3.10, h5py 3.8.0, libhdf5 1.12;
                      # the whole stack uses conda binaries
          - py310  # Python 3.10, all latest versions of dependencies
          - py314  # Python 3.14, all latest versions of dependencies
        include:
          - os: ubuntu-latest
            env: np126  # NumPy 1.26
          - os: ubuntu-latest
            env: np200  # NumPy 2.0 (has special cases not in 2.3)
          - os: ubuntu-latest
            env: h5py-dev  # h5py git tip
        exclude:
          - os: windows-latest
            env: hdf5-112  # Linker issues

      fail-fast: false
    steps:
      - uses: actions/checkout@v6
        with:
          # get correct version from setuptools_scm
          fetch-depth: 0
          fetch-tags: true

      - uses: prefix-dev/setup-pixi@v0
        with:
          pixi-version: v0.61.0
          cache: true
          locked: ${{ matrix.env != 'h5py-dev' }}
          environments: ${{ matrix.env }}

      - name: Update h5py to current git tip
        # This causes h5py to be compiled twice, but only in case of pixi cache miss.
        if: matrix.env == 'h5py-dev'
        run: |
          pixi update -e h5py-dev h5py
          pixi ls -e h5py-dev h5py

      - name: Compile, install, and print versions
        # Trigger environment activation, which in turn performs an editable install
        # of versioned-hdf5.
        # This step is not strictly necessary: we could just run `pixi r test`.
        # We're running it to clearly separate compilation and testing steps.
        # In case of h5py-dev and mindeps, this step also (re)compiles h5py from sources.
        run: pixi r -e ${{ matrix.env }} smoke

      - name: Run Tests
        run: pixi r -e ${{ matrix.env }} test -v
